-- MySQL Script generated by MySQL Workbench
-- Wed Dec 18 22:41:06 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema shopdb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema shopdb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `shopdb` DEFAULT CHARACTER SET utf8 ;
USE `shopdb` ;

-- -----------------------------------------------------
-- Table `shopdb`.`categories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `shopdb`.`categories` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `shopdb`.`products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `shopdb`.`products` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `description` VARCHAR(45) NULL,
  `price` FLOAT NULL,
  `weight` FLOAT NULL,
  `category_id` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `category_fk_idx` (`category_id` ASC) VISIBLE,
  CONSTRAINT `category_fk`
    FOREIGN KEY (`category_id`)
    REFERENCES `shopdb`.`categories` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `shopdb`.`status`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `shopdb`.`status` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `shopdb`.`orders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `shopdb`.`orders` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `confirmation_date` DATETIME NULL,
  `status_id` INT NULL,
  `username` VARCHAR(45) NULL,
  `email` VARCHAR(100) NULL,
  `phonenumber` VARCHAR(12) NULL,
  PRIMARY KEY (`id`),
  INDEX `status_fk_idx` (`status_id` ASC) VISIBLE,
  CONSTRAINT `status_fk`
    FOREIGN KEY (`status_id`)
    REFERENCES `shopdb`.`status` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `shopdb`.`orderlines`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `shopdb`.`orderlines` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `order_id` INT NOT NULL,
  `product_id` INT NULL,
  `quantity` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `order_fk_idx` (`order_id` ASC) VISIBLE,
  INDEX `product_fk_idx` (`product_id` ASC) VISIBLE,
  CONSTRAINT `order_fk`
    FOREIGN KEY (`order_id`)
    REFERENCES `shopdb`.`orders` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `product_fk`
    FOREIGN KEY (`product_id`)
    REFERENCES `shopdb`.`products` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `shopdb`.`status`
-- -----------------------------------------------------
START TRANSACTION;
USE `shopdb`;
INSERT INTO `shopdb`.`status` (`id`, `name`) VALUES (1, 'unconfirmed');
INSERT INTO `shopdb`.`status` (`id`, `name`) VALUES (2, 'confirmed');
INSERT INTO `shopdb`.`status` (`id`, `name`) VALUES (3, 'cancelled');
INSERT INTO `shopdb`.`status` (`id`, `name`) VALUES (4, 'completed');

INSERT INTO `shopdb`.`categories` (`id`, `name`) VALUES (1, 'cat food');
INSERT INTO `shopdb`.`categories` (`id`, `name`) VALUES (2, 'dog food');
INSERT INTO `shopdb`.`categories` (`id`, `name`) VALUES (3, 'cat litter boxes');
INSERT INTO `shopdb`.`categories` (`id`, `name`) VALUES (4, 'cat litter');
INSERT INTO `shopdb`.`categories` (`id`, `name`) VALUES (5, 'cat toys');
INSERT INTO `shopdb`.`categories` (`id`, `name`) VALUES (6, 'dog toys');
INSERT INTO `shopdb`.`categories` (`id`, `name`) VALUES (7, 'beds');
INSERT INTO `shopdb`.`categories` (`id`, `name`) VALUES (8, 'harnesses');

INSERT INTO `shopdb`.`products`
(`id`,`name`,`description`,`price`,`weight`,`category_id`)
VALUES
(1, 'Animonda Tuna','animonda cat food tuna 400g', 5.50, 0.4, 1);
INSERT INTO `shopdb`.`products`
(`id`,`name`,`description`,`price`,`weight`,`category_id`)
VALUES
(2, 'Animonda Beef', 'animonda cat food beef 400g', 6.00, 0.4, 1);
INSERT INTO `shopdb`.`products`
(`id`,`name`,`description`,`price`,`weight`,`category_id`)
VALUES
(3, 'Rocco Classic', 'rocco dog food classic beef 800g', 12.80, 0.8, 2);
INSERT INTO `shopdb`.`products`
(`id`,`name`,`description`,`price`,`weight`,`category_id`)
VALUES
(4, 'Rocco Beef-Salmon', 'rocco dog food beef with salmon 800g', 13.20, 0.8, 2);
INSERT INTO `shopdb`.`products`
(`id`,`name`,`description`,`price`,`weight`,`category_id`)
VALUES
(5, 'CatCentre Luxury Litter Box', 'catcentre litter box blue', 20.00, 0.3, 3);
INSERT INTO `shopdb`.`products`
(`id`,`name`,`description`,`price`,`weight`,`category_id`)
VALUES
(6, 'Purina Cluming Litter', 'purina clumping litter 10kg', 40.00, 10.0, 4);
INSERT INTO `shopdb`.`products`
(`id`,`name`,`description`,`price`,`weight`,`category_id`)
VALUES
(7, 'Cat Wooden Wand', 'cat wooden wand with bird', 12.50, 0.25, 5);
INSERT INTO `shopdb`.`products`
(`id`,`name`,`description`,`price`,`weight`,`category_id`)
VALUES
(8, 'Dog Ball','dog red rubber ball', 5.20, 0.15, 6);

COMMIT;

